# Basket option implementation based on normal model

In [4]:
import numpy as np
from option_models import basket
from option_models import bsm
from option_models import normal

ImportError: cannot import name 'normal_price'

In [2]:
### only run this when you changed the class definition
import imp
imp.reload(basket)

<module 'option_models.basket' from 'D:\\Mega\\PHBS\\@ASP\\2018.M1.ASP\\py\\HW3\\option_models\\basket.py'>

In [3]:
# A trivial test case 1: 
# one asset have 100% weight (the others zero)
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.array([1, 0, 0, 0])
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 120

print(weights)

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)

[1 0 0 0]


In [4]:
# Compare the price to normal model formula

norm1 = normal.NormalModel(40)
price_norm = norm1.price(strike=120, spot=100, texp=texp, cp_sign=1)
print(price_basket, price_norm)

26.7639097343 26.5708459579


In [5]:
# A trivial test case 2
# all assets almost perfectly correlated:
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.0001*np.identity(4) + 0.9999*np.ones((4,4))
texp = 5
strike = 120

print( cor_m )

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)
print(price_basket, price_norm)

[[ 1.      0.9999  0.9999  0.9999]
 [ 0.9999  1.      0.9999  0.9999]
 [ 0.9999  0.9999  1.      0.9999]
 [ 0.9999  0.9999  0.9999  1.    ]]
26.7613956159 26.5708459579


In [16]:
# A full test set for basket option with exact price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 100
price_exact = 28.0073695

In [17]:
cor_m

array([[ 1. ,  0.5,  0.5,  0.5],
       [ 0.5,  1. ,  0.5,  0.5],
       [ 0.5,  0.5,  1. ,  0.5],
       [ 0.5,  0.5,  0.5,  1. ]])

In [19]:
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)
print(price_basket, price_exact)

28.3881270524 28.0073695


# [To Do] Basket option implementation based on BSM model
## Write the similar test for BSM

In [15]:
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=True)

In [ ]:
# A trivial test case 1: 
# one asset have 100% weight (the others zero)
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.array([1, 0, 0, 0])
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 120

print(weights)

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol, weights, texp, cor_m, bsm=True)

# Spread option implementation based on normal model

In [3]:
# A full test set for spread option

spot = np.array([100, 96])
vol = np.array([0.2, 0.1])
weights = np.array([1, -1])
divr = np.array([1, 1])*0.05
intr = 0.1
cor_m = np.array([[1, 0.5], [0.5, 1]])
texp = 1
strike = 0
price_exact = 8.5132252

In [1]:
# MC price based on normal model
# make sure that the prices are similar

np.random.seed(123456)
price_spread = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, intr=intr, divr=divr, bsm=False)
print(price_spread, price_exact)


NameError: name 'np' is not defined

# Spread option implementation based on BSM model

In [6]:
# Once the implementation is finished the BSM model price should also work
price_spread = basket.basket_price_mc(
    strike, spot, vol*spot, weights, texp, cor_m, intr=intr, divr=divr, bsm=True)

In [7]:
# You also test Kirk's approximation
price_kirk = basket.spread_price_kirk(strike, spot, vol, texp, 0.5, intr, divr)
print(price_kirk)

8.51322522955


# [To Do] Complete the implementation of basket_price_norm_analytic
# Compare the MC stdev of BSM basket prices from with and without CV

In [8]:
# The basket option example from above
spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.array([1, 0, 0, 0])
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 120

In [80]:
### Make sure that the analytic normal price is correctly implemented
# basket.basket_price_norm_analytic(strike, spot, vol*spot, weights, texp, cor_m, intr=intr, divr=divr, bsm=False)
np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol, weights, texp, cor_m, bsm=True)
print(price_basket)

In [31]:
# Run below about 100 times and get the mean and stdev
### Returns 2 prices, without CV and with CV 
price_basket = basket.basket_price_mc_cv(strike, spot, vol, weights, texp, cor_m)
print (price_basket)
### Returns 2 prices, without CV and with CV 
# price_basket = basket.basket_price_mc_cv(strike, spot, vol, weights, texp, cor_m)

In [ ]:
# Find the mean and std by calling the function 100 times. 
def MC_est_price(iter_times = 100):
    price_list = []
    price_list_cv = []
    for i in range(iter_times):
        price_basket = basket.basket_price_mc_cv(strike, spot, vol, weights, texp, cor_m)
        price_list.append(price_basket[0])
        price_list_cv.append(price_basket[1])
    MC_est = np.mean(price_list)
    MC_std = np.std(price_list)
    MC_est_cv = np.mean(price_list_cv)
    MC_std_cv = np.std(price_list_cv)
    return [MC_est, MC_std],[MC_est_cv, MC_std_cv]

MC_est_price()